// File generated by the BNF Converter (bnfc 2.9.5).

package org.syntax.stella;

public class AbsynDef {

  public static <B,A extends java.util.LinkedList<? super B>> A cons(B x, A xs) {
    xs.addFirst(x);
    return xs;
  }

  public static org.syntax.stella.Absyn.Pattern patternCons(org.syntax.stella.Absyn.Pattern h, org.syntax.stella.Absyn.Pattern t) {
    return new org.syntax.stella.Absyn.PatternCons(h, t);
  }

}
